CREATE TABLE DIM_ETICHETA (
    ID_ETICHETA    INT            IDENTITY(1,1) NOT NULL
                       CONSTRAINT PK_DIM_ETICHETA PRIMARY KEY,
    NUME_ETICHETA  VARCHAR(60)    NOT NULL,
    CULOARE        VARCHAR(7)     NULL,
    META_JSON      NVARCHAR(MAX)  NULL
                       CONSTRAINT CK_ETICH_JSON
                       CHECK (ISJSON(META_JSON) = 1)
);
GO