SET IDENTITY_INSERT DIM_CATEGORIE ON;
INSERT INTO DIM_CATEGORIE
    (ID_CATEGORIE, NUME_CATEGORIE, CATEGORIE_PARINTE, ACTIVA, META_JSON)
VALUES
    (7, 'Sport', NULL, 1,
     '{"prioritate_strategica":"medie","obiectiv_lunar":4}');
SET IDENTITY_INSERT DIM_CATEGORIE OFF;
GO

SELECT * FROM DIM_CATEGORIE WHERE ID_CATEGORIE = 7;
GO