SET IDENTITY_INSERT DIM_UTILIZATOR ON;
INSERT INTO DIM_UTILIZATOR
    (ID_UTILIZATOR,NUME,PRENUME,ROL,ACTIV,
     DATA_INREGISTRARE,ULTIMA_AUTENTIFICARE,SEGMENT_JSON)
VALUES
    (20,'Ionescu','Mihai','cititor',1,
     '2026-04-05','2026-04-05',
     '{"comportament":"nou","risc_abandon":"necunoscut"}');
SET IDENTITY_INSERT DIM_UTILIZATOR OFF;
GO
SELECT * FROM DIM_UTILIZATOR WHERE ID_UTILIZATOR = 20;
GO