INSERT INTO FACT_DWH_GESTIUNE_ARTICOLE
(ID_TIMP,ID_ARTICOL,ID_AUTOR,ID_CATEGORIE,ID_UTILIZATOR,
 ID_ETICHETA,ID_ROL,ID_STATUS,
 NR_VIZUALIZARI,DURATA_MEDIE_SEC,RATA_VIZUALIZARE,
 NR_ARTICOLE_PUBLICATE,NR_ARTICOLE_CREATE,RATA_PUBLICARE,
 NR_COMENTARII,RATA_COMENTARE,MEDIE_EVALUARE,
 NR_ARTICOLE_CATEGORIE,NR_VERSIUNI,RATA_ACTUALIZARE,
 NR_SESIUNI_ACTIVE,RATA_AUTENTIFICARE,RATA_RETENTIE,
 KPI_METADATA_JSON)
VALUES
(7,30,2,1,20,
 2,3,1,
 12,310.00,0.0588,
 9,13,0.6923,
 2,0.1667,5.00,
 19,1,0.0526,
 1,0.0500,0.0500,
 '{"articol":"ML Python Ghid","utilizator_nou":"Ionescu_Mihai","luna":"Aprilie_2026"}');
GO
SELECT TOP 3 ID_FAPT_DWH, ID_TIMP, ID_ARTICOL,
             NR_VIZUALIZARI, MEDIE_EVALUARE,
             JSON_VALUE(KPI_METADATA_JSON,'$.luna') AS LUNA
FROM FACT_DWH_GESTIUNE_ARTICOLE
ORDER BY ID_FAPT_DWH DESC;
GO