SELECT COUNT(*) AS REFERINTE_FACT
FROM FACT_DWH_GESTIUNE_ARTICOLE
WHERE ID_ARTICOL = 9;
GO
DELETE FROM FACT_DWH_GESTIUNE_ARTICOLE
WHERE ID_ARTICOL = 9
  AND ID_FAPT_DWH IN (
      SELECT f.ID_FAPT_DWH
      FROM FACT_DWH_GESTIUNE_ARTICOLE f
      JOIN DIM_ARTICOL ar ON f.ID_ARTICOL = ar.ID_ARTICOL
      WHERE ar.STATUS = 'draft'
        AND ar.DATA_PUBLICARII IS NULL
  );
GO
DELETE FROM DIM_ARTICOL
WHERE ID_ARTICOL = 9 AND STATUS = 'draft';
GO
SELECT COUNT(*) AS ARTICOLE_RAMASE FROM DIM_ARTICOL;
GO