SELECT
    ar.TITLU,
    c.NUME_CATEGORIE,
    a.NUME + ' ' + a.PRENUME                AS AUTOR,
    t.DENUMIRE_LUNA + ' ' + CAST(t.AN AS VARCHAR) AS PERIOADA,
    f.NR_VIZUALIZARI,
    f.MEDIE_EVALUARE,
    f.RATA_COMENTARE,
    JSON_VALUE(ar.ATRIBUTE_JSON,'$.nivel')   AS NIVEL
FROM FACT_DWH_GESTIUNE_ARTICOLE f
JOIN DIM_ARTICOL   ar ON f.ID_ARTICOL   = ar.ID_ARTICOL
JOIN DIM_CATEGORIE  c ON f.ID_CATEGORIE = c.ID_CATEGORIE
JOIN DIM_AUTOR      a ON f.ID_AUTOR     = a.ID_AUTOR
JOIN DIM_TIMP       t ON f.ID_TIMP      = t.ID_TIMP
WHERE ar.STATUS = 'publicat'
ORDER BY f.NR_VIZUALIZARI DESC;
GO