SELECT
    ID_CATEGORIE,
    NUME_CATEGORIE,
    ACTIVA,
    JSON_VALUE(META_JSON,'$.prioritate_strategica') AS PRIORITATE,
    JSON_VALUE(META_JSON,'$.obiectiv_lunar')         AS OBIECTIV_LUNAR
FROM DIM_CATEGORIE
WHERE ACTIVA = 1
ORDER BY NUME_CATEGORIE;
GO