SELECT
    u.NUME + ' ' + u.PRENUME               AS UTILIZATOR,
    u.ROL,
    u.ACTIV,
    u.ULTIMA_AUTENTIFICARE,
    JSON_VALUE(u.SEGMENT_JSON,'$.risc_abandon') AS RISC_ABANDON,
    JSON_VALUE(u.SEGMENT_JSON,'$.comportament') AS COMPORTAMENT,
    AVG(f.RATA_RETENTIE)                    AS RETENTIE_MEDIE
FROM DIM_UTILIZATOR u
LEFT JOIN FACT_DWH_GESTIUNE_ARTICOLE f ON u.ID_UTILIZATOR = f.ID_UTILIZATOR
GROUP BY u.NUME, u.PRENUME, u.ROL, u.ACTIV,
         u.ULTIMA_AUTENTIFICARE, u.SEGMENT_JSON
ORDER BY RETENTIE_MEDIE ASC;
GO