USE DWH_KPI1_PerformantaArticolelor;
GO
DROP TABLE IF EXISTS FACT_PERFORMANTA_ARTICOLE;
DROP TABLE IF EXISTS DIM_ARTICOL_KPI1;
DROP TABLE IF EXISTS DIM_AUTOR_KPI1;
DROP TABLE IF EXISTS DIM_CATEGORIE_KPI1;
DROP TABLE IF EXISTS DIM_TIMP_KPI1;
CREATE TABLE DIM_TIMP_KPI1 (
    ID_TIMP        INT PRIMARY KEY,
    DATA_COMPLETA  DATE,
    ZI             INT,
    LUNA           INT,
    DENUMIRE_LUNA  VARCHAR(20),
    TRIMESTRU      INT,
    SEMESTRU       INT,
    AN             INT,
    ZI_SAPTAMANA   VARCHAR(20),
    ESTE_ZI_LUCRATOARE TINYINT
);
CREATE TABLE DIM_ARTICOL_KPI1 (
    ID_ARTICOL       INT PRIMARY KEY,
    TITLU            VARCHAR(255),
    SLUG             VARCHAR(255),
    STATUS           VARCHAR(20),
    DATA_PUBLICARII  DATETIME,
    DATA_MODIFICARII DATETIME
);
CREATE TABLE DIM_AUTOR_KPI1 (
    ID_AUTOR          INT PRIMARY KEY,
    NUME              VARCHAR(100),
    PRENUME           VARCHAR(100),
    EMAIL             VARCHAR(100),
    ROL               VARCHAR(50),
    DATA_INREGISTRARE DATETIME
);
CREATE TABLE DIM_CATEGORIE_KPI1 (
    ID_CATEGORIE      INT PRIMARY KEY,
    NUME_CATEGORIE    VARCHAR(100),
    CATEGORIE_PARINTE INT,
    ACTIVA            TINYINT
);
CREATE TABLE FACT_PERFORMANTA_ARTICOLE (
    ID_FAPT          INT IDENTITY(1,1) PRIMARY KEY,
    ID_TIMP          INT FOREIGN KEY REFERENCES DIM_TIMP_KPI1(ID_TIMP),
    ID_ARTICOL       INT FOREIGN KEY REFERENCES DIM_ARTICOL_KPI1(ID_ARTICOL),
    ID_AUTOR         INT FOREIGN KEY REFERENCES DIM_AUTOR_KPI1(ID_AUTOR),
    ID_CATEGORIE     INT FOREIGN KEY REFERENCES DIM_CATEGORIE_KPI1(ID_CATEGORIE),
    NR_VIZUALIZARI   INT,
    DURATA_MEDIE_SEC DECIMAL(10,2),
    RATA_VIZUALIZARE DECIMAL(10,2)
);
GO
INSERT INTO DIM_TIMP_KPI1
SELECT ID_TIMP, DATA_COMPLETA, ZI, LUNA, DENUMIRE_LUNA,
       TRIMESTRU, SEMESTRU, AN, ZI_SAPTAMANA, ESTE_ZI_LUCRATOARE
FROM DWH_GestionareArticole.dbo.DIM_TIMP;
INSERT INTO DIM_ARTICOL_KPI1
SELECT ID_ARTICOL, TITLU, SLUG, STATUS, DATA_PUBLICARII, DATA_MODIFICARII
FROM DWH_GestionareArticole.dbo.DIM_ARTICOL;
INSERT INTO DIM_AUTOR_KPI1
SELECT ID_AUTOR, NUME, PRENUME, EMAIL, ROL, DATA_INREGISTRARE
FROM DWH_GestionareArticole.dbo.DIM_AUTOR;
INSERT INTO DIM_CATEGORIE_KPI1
SELECT ID_CATEGORIE, NUME_CATEGORIE, CATEGORIE_PARINTE, ACTIVA
FROM DWH_GestionareArticole.dbo.DIM_CATEGORIE;
INSERT INTO FACT_PERFORMANTA_ARTICOLE
    (ID_TIMP, ID_ARTICOL, ID_AUTOR, ID_CATEGORIE,
     NR_VIZUALIZARI, DURATA_MEDIE_SEC, RATA_VIZUALIZARE)
SELECT ID_TIMP, ID_ARTICOL, ID_AUTOR, ID_CATEGORIE,
       NR_VIZUALIZARI, DURATA_MEDIE_SEC, RATA_VIZUALIZARE
FROM DWH_GestionareArticole.dbo.FACT_DWH_GESTIUNE_ARTICOLE;
GO