USE DWH_KPI2_ActivitateaAutorilor;
GO
DROP TABLE IF EXISTS FACT_ACTIVITATE_AUTORI;
DROP TABLE IF EXISTS DIM_AUTOR_KPI2;
DROP TABLE IF EXISTS DIM_CATEGORIE_KPI2;
DROP TABLE IF EXISTS DIM_TIMP_KPI2;
CREATE TABLE DIM_TIMP_KPI2 (
    ID_TIMP        INT PRIMARY KEY,
    DATA_COMPLETA  DATE,
    ZI             INT,
    LUNA           INT,
    DENUMIRE_LUNA  VARCHAR(20),
    AN             INT
);
CREATE TABLE DIM_AUTOR_KPI2 (
    ID_AUTOR          INT PRIMARY KEY,
    NUME              VARCHAR(100),
    PRENUME           VARCHAR(100),
    EMAIL             VARCHAR(100),
    ROL               VARCHAR(50),
    DATA_INREGISTRARE DATETIME
);
CREATE TABLE DIM_CATEGORIE_KPI2 (
    ID_CATEGORIE   INT PRIMARY KEY,
    NUME_CATEGORIE VARCHAR(100),
    ACTIVA         TINYINT
);
CREATE TABLE FACT_ACTIVITATE_AUTORI (
    ID_FAPT               INT IDENTITY(1,1) PRIMARY KEY,
    ID_TIMP               INT FOREIGN KEY REFERENCES DIM_TIMP_KPI2(ID_TIMP),
    ID_AUTOR              INT FOREIGN KEY REFERENCES DIM_AUTOR_KPI2(ID_AUTOR),
    ID_CATEGORIE          INT FOREIGN KEY REFERENCES DIM_CATEGORIE_KPI2(ID_CATEGORIE),
    NR_ARTICOLE_PUBLICATE INT,
    NR_ARTICOLE_CREATE    INT,
    RATA_PUBLICARE        DECIMAL(10,2)
);
GO
INSERT INTO DIM_TIMP_KPI2
SELECT ID_TIMP, DATA_COMPLETA, ZI, LUNA, DENUMIRE_LUNA, AN
FROM DWH_GestionareArticole.dbo.DIM_TIMP;
INSERT INTO DIM_AUTOR_KPI2
SELECT ID_AUTOR, NUME, PRENUME, EMAIL, ROL, DATA_INREGISTRARE
FROM DWH_GestionareArticole.dbo.DIM_AUTOR;
INSERT INTO DIM_CATEGORIE_KPI2
SELECT ID_CATEGORIE, NUME_CATEGORIE, ACTIVA
FROM DWH_GestionareArticole.dbo.DIM_CATEGORIE;
INSERT INTO FACT_ACTIVITATE_AUTORI
    (ID_TIMP, ID_AUTOR, ID_CATEGORIE,
     NR_ARTICOLE_PUBLICATE, NR_ARTICOLE_CREATE, RATA_PUBLICARE)
SELECT ID_TIMP, ID_AUTOR, ID_CATEGORIE,
       NR_ARTICOLE_PUBLICATE, NR_ARTICOLE_CREATE, RATA_PUBLICARE
FROM DWH_GestionareArticole.dbo.FACT_DWH_GESTIUNE_ARTICOLE;
GO