USE DWH_KPI3_EngagementUtilizatori;
GO
DROP TABLE IF EXISTS FACT_ENGAGEMENT_UTILIZATORI;
DROP TABLE IF EXISTS DIM_ARTICOL_KPI3;
DROP TABLE IF EXISTS DIM_UTILIZATOR_KPI3;
DROP TABLE IF EXISTS DIM_TIMP_KPI3;
CREATE TABLE DIM_TIMP_KPI3 (
    ID_TIMP       INT PRIMARY KEY,
    DATA_COMPLETA DATE,
    ZI            INT,
    LUNA          INT,
    AN            INT
);
CREATE TABLE DIM_ARTICOL_KPI3 (
    ID_ARTICOL INT PRIMARY KEY,
    TITLU      VARCHAR(255),
    STATUS     VARCHAR(20)
);
CREATE TABLE DIM_UTILIZATOR_KPI3 (
    ID_UTILIZATOR     INT PRIMARY KEY,
    NUME              VARCHAR(100),
    PRENUME           VARCHAR(100),
    ROL               VARCHAR(50),
    ACTIV             TINYINT,
    DATA_INREGISTRARE DATETIME
);
CREATE TABLE FACT_ENGAGEMENT_UTILIZATORI (
    ID_FAPT         INT IDENTITY(1,1) PRIMARY KEY,
    ID_TIMP         INT FOREIGN KEY REFERENCES DIM_TIMP_KPI3(ID_TIMP),
    ID_ARTICOL      INT FOREIGN KEY REFERENCES DIM_ARTICOL_KPI3(ID_ARTICOL),
    ID_UTILIZATOR   INT FOREIGN KEY REFERENCES DIM_UTILIZATOR_KPI3(ID_UTILIZATOR),
    NR_COMENTARII   INT,
    RATA_COMENTARE  DECIMAL(10,2),
    MEDIE_EVALUARE  DECIMAL(10,2)
);
GO
INSERT INTO DIM_TIMP_KPI3
SELECT ID_TIMP, DATA_COMPLETA, ZI, LUNA, AN
FROM DWH_GestionareArticole.dbo.DIM_TIMP;
INSERT INTO DIM_ARTICOL_KPI3
SELECT ID_ARTICOL, TITLU, STATUS
FROM DWH_GestionareArticole.dbo.DIM_ARTICOL;
INSERT INTO DIM_UTILIZATOR_KPI3
SELECT ID_UTILIZATOR, NUME, PRENUME, ROL, ACTIV, DATA_INREGISTRARE
FROM DWH_GestionareArticole.dbo.DIM_UTILIZATOR;
INSERT INTO FACT_ENGAGEMENT_UTILIZATORI
    (ID_TIMP, ID_ARTICOL, ID_UTILIZATOR,
     NR_COMENTARII, RATA_COMENTARE, MEDIE_EVALUARE)
SELECT ID_TIMP, ID_ARTICOL, ID_UTILIZATOR,
       NR_COMENTARII, RATA_COMENTARE, MEDIE_EVALUARE
FROM DWH_GestionareArticole.dbo.FACT_DWH_GESTIUNE_ARTICOLE;
GO